# Generated by Django 5.2.11 on 2026-03-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-friendly identifier, e.g. 'galerie-fontana'", max_length=200, unique=True)),
                ('name', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, default='', help_text='Supports Markdown.')),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('phone2', models.CharField(blank=True, db_column='Phone2', default='', max_length=50)),
                ('image_link', models.CharField(blank=True, db_column='ImageLink', default='', help_text='Cloud image path, e.g. /cloud/website-images/galerie-fontana.jpg', max_length=500)),
                ('image_alt', models.CharField(blank=True, db_column='ImageAlt', default='', max_length=400)),
                ('sortorder', models.IntegerField(db_column='SortOrder', default=0)),
                ('do_not_show', models.BooleanField(db_column='DoNotShow', default=False)),
                ('place', models.ForeignKey(db_column='PlaceId', on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='core.place')),
            ],
            options={
                'db_table': 'Galleries',
                'ordering': ['sortorder', 'name'],
            },
        ),
    ]
