# Generated by Django 5.2.11 on 2026-03-01 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_add_currency_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_link',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
