# Generated by Django 5.2.11 on 2026-03-03 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The visible link text / button label.', max_length=400)),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True, default='', help_text='Optional paragraph of body text shown below the link.')),
                ('sortorder', models.IntegerField(db_column='SortOrder', default=0)),
                ('do_not_show', models.BooleanField(db_column='DoNotShow', default=False)),
            ],
            options={
                'verbose_name_plural': 'links',
                'db_table': 'Links',
                'ordering': ['sortorder', 'id'],
            },
        ),
    ]
