# Generated by Django 5.2.11 on 2026-03-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='UpdatedAt', help_text='Automatically set to now whenever the link is saved.'),
        ),
    ]
